web: bench serve --port 8000
socketio: node apps/frappe/socketio.js
schedule: bench schedule
worker_short: bench worker --queue short
worker_default: bench worker --queue default
worker_long: bench worker --queue long
